frigid-lynx/Hacktoberfest2022

- number to words.java
This programs converts an integer to words in java  for example:-
INPUT- "9982"
OUTPUT-" nine hundred eighty two"
> number to words.java

- trappingRainWater.java
leetcode two pointer hard problem
> Created trappingRainWater.java

- calculator.java
> Added calculator.java

- Linear_search.java
Added a java program for linear search.
> Java program for linear search

- encryption.java
- sudoko.java
- sudukogen.java
- tictactoe.java
add java program for suduko gen ,solving,encryption of text and tictac toe
> java program (sudoku gen , solving encryption of text and tic-tac-toe)

- CountingSort.java
Added Counting Sort algorithm to the Sorting Algorithms section.
>  CountingSort algorithm in java

- BinarySearchJavaHacktoberfest2022
Created Binary Search By Using Java.
> BinarySearch.java

- Count of Smaller Numbers After Self.java
You are given an integer array nums and you have to return a new counts array. The counts array has the property where counts[i] is the number of smaller elements to the right of nums[i].
Input: nums = [5,2,6,1]
Output: [2,1,1,0]
Explanation:
To the right of 5 there are 2 smaller elements (2 and 1). To the right of 2 there is only 1 smaller element (1). To the right of 6 there is 1 smaller element (1).
To the right of 1 there is 0 smaller element.
> Count of Smaller Numbers After Self

- Pyramid_pattern.java
Added a java code to print pyramid pattern
> Pyramid pattern using java

- Reverse_string.java
This is a program which takes input in string form and return the reverse of the string.
This program is written in java .
> Reverse String in java

- Fibonacci_number
This is a fabonacci number program . This program return the fabonacci number in order.
> Fibonacci Number

- Triangle_pattern.java
Added a java code to print triangle pattern
> Java code to print triangular pattern

- N_Queen_Backtracking.java
Added N Queen Problem
Hope you will merge it
Thank you very much
> N Queen Problem

- kthElementInTheArray.cpp
> KthElement

- Kadane's_algo.java
This is the Kadane's_algo using java.
> Kadane's_algo.java

- rotateTheBox.java
added new program: rotateTheBOX
> rotateTheBox.java solution of Hackerrank problem

- Recurrsion in java
The process in which a function calls itself directly or indirectly is called recursion and the corresponding function is called as recursive function. Using recursive algorithm, certain problems can be solved quite easily.
> Create Recurrsion in java

- Detect Capital.java
Create Detect Capital.java added
> Added one LeetCode problem in java

- MinimumPathSum.java
Problem link : https://leetcode.com/problems/minimum-path-sum/
Image of Successfully submited ✔
> Added 64th leetcode problem (MinPathSum), solved by Recursion + dp

- complexNum.java
Added Complex Num function
hope you will merge it
Thank you
> Added ComplexNum file

- linkedlist.java
created linkedlist.java for building linkedlist from scratch
> created linkedlist.java

- PalPrime number
The PalPrime number is a special positive number which is also known as the Palindromic Prime number. A number is said to be a palindromic prime if the number is a palindrome as well as a prime.
> Create PalPrime number

- Fibonacci series/RV fibonacci series
Hello sir , i hope you are doing well please merge my pull request
> FIBONACCI SERIES HF22

- specialdigit.java
a special two-digit number is a number such that the sum of its digits when added to the product of its digits gives the original number itself.
> a special two digit number
